# DB
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

# DEV (lokal PostgreSQL)
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/p2p_db

# PROD
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/p2p_db

quarkus.console.enabled=false

# Testcontainers off
quarkus.datasource.devservices.enabled=false

# Flyway
quarkus.flyway.migrate-at-start=true

# JWT
mp.jwt.verify.issuer=kompetenz-app
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem