# DB
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

app.admin.id=00000000-0000-0000-0000-000000000001
app.admin.username=admin
app.admin.email=admin@kompetenz.de
app.admin.password=admin123

# DEV (lokal PostgreSQL)
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/p2p_db

# PROD
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/p2p_db

quarkus.console.enabled=false

# Testcontainers off
quarkus.datasource.devservices.enabled=false

# Flyway
quarkus.flyway.migrate-at-start=true

# Gemini embedding configuration
gemini.api.key=${GEMINI_API_KEY:}
gemini.embedding.model=gemini-embedding-001
embedding.backfill.enabled=false

# JWT
mp.jwt.verify.issuer=kompetenz-app
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
